environment: development

http:
  port: 8080

postgres:
  host: localhost
  port: 5433
  username:
  password:
  params:
  database: cloud-native-shop-db
  appName: cloud-native-shop
  minPoolSize: 5
  maxPoolSize: 100

redis:
  host: localhost
  port: 6380
  password: ""
  database: 0

log:
  level: debug
